version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4

jobs:
  build_and_test:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install

      - run:
          name: Run tests
          command: |
            npm test
  
  deploy_to_elasticbeanstalk: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Deploy to Elastic Beanstalk 
          command: |
            eb --version
            eb deploy $EB_ENVIRONMENT
            eb status

  

workflows:
  my_workflow:
    jobs:
      # - build_and_test
      - deploy_to_elasticbeanstalk
