version: 2.1

orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0

jobs:
  build_and_test:
    working_directory: ~/app
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install

      - run:
          name: Run tests
          command: |
            npm test
  
  deploy_to_elasticbeanstalk: 
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - eb/setup
      - run:
          name: Deploy to Elastic Beanstalk 
          command: |
            eb --version
            eb deploy $EB_ENVIRONMENT
            eb status

  

workflows:
  my_workflow:
    jobs:
      - build_and_test
      - deploy_to_elasticbeanstalk
