version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.4

jobs:
  deploy:
    working_directory: ~/app
    docker:
      - image: node:14
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            npm install

      - run:
          name: Run tests
          command: |
            npm test

      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            eb deploy $EB_ENVIRONMENT

workflows:
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
