version: 2.1

# orbs:
#   aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build_and_test:
    working_directory: ~/app
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install

      - run:
          name: Run tests
          command: |
            npm test
  
  deploy_to_elasticbeanstalk: 
    docker:
      - image: cimg/aws:2023.01
    steps:
      - checkout
      - run:
          name: Deploy to Elastic Beanstalk 
          command: |
            eb --version
            eb deploy $EB_ENVIRONMENT

  

workflows:
  my_workflow:
    jobs:
      - build_and_test
      - deploy_to_elasticbeanstalk
