version: 2.1

orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build_and_test:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install

      - run:
          name: Run tests
          command: |
            npm test
  

workflows:
  my_workflow:
    jobs:
      - build_and_test
      - eb/deploy:
          context: aws-credentials
          application-name: $EB_NAME
          environment-name: $EB_ENVIRONMENT
          platform-version: Node.js 16 running on 64bit Amazon Linux 2
          requires:
            - build_and_test
