version: 2.1

orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  deploy:
    working_directory: ~/app
    docker:
      - image: node:14
    steps:
      - checkout

      - run:
          name: Install dependencies
          working_directory: /
          command: |
            npm install

      - run:
          name: Run tests
          working_directory: /
          command: |
            npm test

      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            eb deploy $EB_ENVIRONMENT

workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
